### ISSUE TITLE
blog: [Freshman-Advice]

### ISSUE THREAD

**Issue by Ashishjob** [CougarCS/CougarCS-Docs#1]
# Blog [Freshman-Advice]

[x] Adding new blog?
[] Changes to preexisting blog (Must be your own)

## Why?
Does this blog add value to CougarCS, students career, or academic journey?

- Some people have already seen it and claimed for it to be a useful guide for first years entering UH in CS.

**Comment by Brodypen** [comment]
Sounds like a great idea!
