### ISSUE TITLE
feat: Tech Documentation Advice

### ISSUE THREAD

**Issue by Ashishjob** [CougarCS/CougarCS-Docs#3]
**Is your feature request related to a problem? Please describe.**
> Sometimes it's easier to understand documentation for new languages/frameworks/technologies that you're messing around with by hearing it spoken in more generalized and simple terms by people who are closer to your level of understanding rather than the individuals who made the languages/frameworks/technologies.

**Describe the solution you'd like**
> It would be very similar to the other advice blog posts but kept more organized by marking it under a section of its own for a more technical side instead of a general advice side.

**Describe alternatives you've considered**
> Other things could be to link general documentation, but that goes against the idea of people not being able to overcome the learning curve.

**Additional context**
> This concept can honestly also be cut down to a more general approach of just sectioning off branches of blog posts from tech documentation to advice at UH to financial advice.

**Comment by Brodypen** [comment]
I think there is better for our discord, tech threads.
