### ISSUE TITLE
blog: [BLOG] Undergrad Research Opportunities at UH

### ISSUE THREAD

**Issue by Ashishjob** [CougarCS/CougarCS-Docs#4]
# Blog

- [x] Adding a new blog?
- [ ] Changes to preexisting blog (Must be your own)

## Why?
Does this blog add value to CougarCS, students' careers, or academic journey?

People have recently been getting into undergraduate research at UH or just in general, and these questions always got directed towards me, it took me some time to send a list of everything that I knew at the top of my head and add advice and other information to it, so I thought it would be nice to compile a list of research just like how we have repos for Internship opportunities!

**Comment by Brodypen** [comment]
Approved! Please send this over!
